# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag jhbarneb/spinnakertest:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          run: docker push jhbarneb/spinnakertest:${{steps.vars.outputs.tag}}
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag jhbarneb/spinnakertest:latest
        - name: Push the latest Docker image
          run: docker push jhbarneb/spinnakertest:latest
